// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcnUJycqbtDpv1ZdhA7KoDOza5A2Pj5B0',
    appId: '1:725312163058:android:096a21e458125d3398546b',
    messagingSenderId: '725312163058',
    projectId: 'kotizpull',
    storageBucket: 'kotizpull.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSxcp2Kj3wG-rP4YikPF_n-aeGNrxZnu0',
    appId: '1:725312163058:ios:73d636c6ec8ef22298546b',
    messagingSenderId: '725312163058',
    projectId: 'kotizpull',
    storageBucket: 'kotizpull.firebasestorage.app',
    iosBundleId: 'com.example.kotizApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxcp2Kj3wG-rP4YikPF_n-aeGNrxZnu0',
    appId: '1:725312163058:web:73d636c6ec8ef22298546b',
    messagingSenderId: '725312163058',
    projectId: 'kotizpull',
    authDomain: 'kotizpull.firebaseapp.com',
    storageBucket: 'kotizpull.firebasestorage.app',
  );
}
